### ISSUE TITLE
provisioner_spec.rb "should assign a random name to the node" is flaky

### ISSUE THREAD

**Issue by leinster** [Atalanta/cucumber-chef#15]
Node information isn't immediately available via search (TestLab#nodes) so the test sometimes falls over.

**Comment by SFEley** [comment]
I ran into this too.  Addressed in pull request #26.

**Comment by leinster** [comment]
Still a problem - the node is getting the correct name but the node information isn't available at the time it's requested.
