### ISSUE TITLE
404 "Not Found" (Net::HTTPServerException)

### ISSUE THREAD

**Issue by aolchik** [Atalanta/cucumber-chef#39]
Hello, I'm starting to try chef using cucumber-chef and when executing
cucumber-chef setup I'm getting the following message

.rvm/rubies/ruby-1.8.7-p352/lib/ruby/1.8/net/http.rb:2105:in `error!':
404 "Not Found" (Net::HTTPServerException)

Any idea of the potential reason for this problem?

**Comment by AlexeyDemidov** [comment]
Same problem here

```
Platform provisioned.  Run cucumber-chef project to get started.
/home/alexd/.rvm/rubies/ruby-1.8.7-p330/lib/ruby/1.8/net/http.rb:2105:in `error!': 404 "Not Found" (Net::HTTPServerException)
        from /home/alexd/.rvm/gems/ruby-1.8.7-p330@chef/gems/chef-0.10.4/lib/chef/rest.rb:237:in `api_request'
        from /home/alexd/.rvm/gems/ruby-1.8.7-p330@chef/gems/chef-0.10.4/lib/chef/rest.rb:288:in `retriable_rest_request'
        from /home/alexd/.rvm/gems/ruby-1.8.7-p330@chef/gems/chef-0.10.4/lib/chef/rest.rb:218:in `api_request'
        from /home/alexd/.rvm/gems/ruby-1.8.7-p330@chef/gems/chef-0.10.4/lib/chef/rest.rb:114:in `get_rest'
        from /home/alexd/.rvm/gems/ruby-1.8.7-p330@chef/gems/chef-0.10.4/lib/chef/node.rb:603:in `load'
        from /home/alexd/.rvm/gems/ruby-1.8.7-p330@chef/gems/cucumber-chef-1.0.3/lib/cucumber/chef/provisioner.rb:74:in `tag_node'
        from /home/alexd/.rvm/gems/ruby-1.8.7-p330@chef/gems/cucumber-chef-1.0.3/lib/cucumber/chef/provisioner.rb:30:in `bootstrap_node'
        from /home/alexd/.rvm/gems/ruby-1.8.7-p330@chef/gems/cucumber-chef-1.0.3/bin/cucumber-chef:63:in `setup'
        from /home/alexd/.rvm/gems/ruby-1.8.7-p330@chef/gems/thor-0.14.6/lib/thor/task.rb:22:in `send'
        from /home/alexd/.rvm/gems/ruby-1.8.7-p330@chef/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
        from /home/alexd/.rvm/gems/ruby-1.8.7-p330@chef/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
        from /home/alexd/.rvm/gems/ruby-1.8.7-p330@chef/gems/thor-0.14.6/lib/thor.rb:263:in `dispatch'
        from /home/alexd/.rvm/gems/ruby-1.8.7-p330@chef/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
        from /home/alexd/.rvm/gems/ruby-1.8.7-p330@chef/gems/cucumber-chef-1.0.3/bin/cucumber-chef:123
        from /home/alexd/.rvm/gems/ruby-1.8.7-p330@chef/bin/cucumber-chef:19:in `load'
        from /home/alexd/.rvm/gems/ruby-1.8.7-p330@chef/bin/cucumber-chef:19
```

**Comment by AlexeyDemidov** [comment]
Resolved - It is necessary to run  `knife node create cucumber-chef-test-lab` before trying to execute `cucumber-chef setup`. This is not documented anywhere.

**Comment by RobertLowe** [comment]
+1

**Comment by Atalanta** [comment]
This shouldn't be necessary.  Can you still reproduce this issue? In the RC this is not a problem.
